export const data = [
  {
    forks: 243,
    name: 'gatsby-themes',
    stars: 745,
    url: 'https://github.com/LekoArts/gatsby-themes',
    createdAt: '2020-07-17',
    id: '1',
  },
  {
    forks: 154,
    name: 'gatsby-starter-minimal-blog',
    stars: 517,
    url: 'https://github.com/LekoArts/gatsby-starter-minimal-blog',
    createdAt: '2020-07-17',
    id: '2',
  },
  {
    forks: 19,
    name: 'gatsby-starter-portfolio-bella',
    stars: 113,
    url: 'https://github.com/LekoArts/gatsby-starter-portfolio-bella',
    createdAt: '2020-07-17',
    id: '3',
  },
  {
    forks: 245,
    name: 'gatsby-themes',
    stars: 749,
    url: 'https://github.com/LekoArts/gatsby-themes',
    createdAt: '2020-07-18',
    id: '4',
  },
  {
    forks: 153,
    name: 'gatsby-starter-minimal-blog',
    stars: 517,
    url: 'https://github.com/LekoArts/gatsby-starter-minimal-blog',
    createdAt: '2020-07-18',
    id: '5',
  },
  {
    forks: 18,
    name: 'gatsby-starter-portfolio-bella',
    stars: 113,
    url: 'https://github.com/LekoArts/gatsby-starter-portfolio-bella',
    createdAt: '2020-07-18',
    id: '6',
  },
]
