name: Build site on Gatsby Cloud
on:
  schedule:
    - cron: "10 12 * * *"
jobs:
  buildSite:
    name: Build site on Gatsby Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Webhook Trigger
        uses: ./.github/actions/webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
