name: Build site on Netlify
on:
  workflow_dispatch:
  schedule:
    - cron: '10 12 * * *'
jobs:
  buildSite:
    name: Build site on Gatsby Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.WEBHOOK_URL }}
