name: Build site on Gatsby Cloud
on:
  schedule:
    - cron: "10 12 * * *"
jobs:
  buildSite:
    name: Build site on Gatsby Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.WEBHOOK_URL }}
