name: Upload to AWS
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
jobs:
  pushAndPull:
    name: Push and Pull Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push and Pull Data
        uses: ./.github/actions/pull-push-data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITTER_API: ${{ secrets.TWITTER_API }}
          AWS_GRAPHQL_API: ${{ secrets.AWS_GRAPHQL_API }}
          AWS_TOKEN: ${{ secrets.AWS_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
