name: Upload to Supabase
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 1 * *'
jobs:
  pushAndPull:
    name: Push and Pull Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push and Pull Data
        uses: ./.github/actions/supabase
        env:
          SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          MASTODON_ACCOUNT_ID: ${{ vars.MASTODON_ACCOUNT_ID }}
          TRAKT_USERNAME: ${{ vars.TRAKT_USERNAME }}
