name: Upload to Turso
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * MON'
jobs:
  pushAndPull:
    name: Push and Pull Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/pnpm-install
      - name: Push and Pull Data
        run: npm run db:insert
        env:
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          MASTODON_ACCOUNT_ID: ${{ vars.MASTODON_ACCOUNT_ID }}
          TRAKT_USERNAME: ${{ vars.TRAKT_USERNAME }}
          BLUESKY_HANDLE: ${{ vars.BLUESKY_HANDLE }}
